.\" manpager - system manual page viewer
.\" Copyright (C) 2017 Tycho Softworks
.\"
.\" This manual page is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU Lesser General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" This manual page is written especially for Debian GNU/Linux.
.\"
.TH manpager "1" "August 2017" "ManPager" "Tycho Softworks"
.SH NAME
manpager \- system manual page viewer
.SH SYNOPSIS
.B manpager
.RB [ options ]
.SH DESCRIPTION
.B manpager
is a simple system manual page viewer utility.  A tabbed index and tabbed view of currently
open manual pages is shown.  A given manual page view can also be searched for text.
.SH OPTIONS
.TP
.B --reset
Resets saved config file.  This also resets the man page search paths to system defaults.
.TP
.B --version
Prints the currently installed version of
.B manpager
to standard out.
.SH AUTHOR
.B manpager
was written by David Sugar <tychosoft@gmail.com>.
.SH COPYRIGHT
Copyright \(co 2017 Tycho Softworks.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.


